### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by equisde** [bakhti31/game-automation#1]
this is currently working or not?

**Comment by equisde** [comment]
is there any possibility to get access to your repo and push some changes to bountyhunter also i want to see if i can make a netcoin miner (i think i can't do that) at least i modified bountyhunter so if there's a bounty it detects the level and start to detect it as you made it but i improved it a little

**Comment by bakhti31** [comment]
Ah sorry , i didnt maintain this again, but i think this is still work, but
if u want to update that maybe i can give u an idea to do it

Pada tanggal Sab, 11 Mar 2023 13.04, Parallax#1520 ***@***.***>
menulis:

**Comment by bakhti31** [comment]
> is there any possibility to get access to your repo and push some changes to bountyhunter also i want to see if i can make a netcoin miner (i think i can't do that) at least i modified bountyhunter so if there's a bounty it detects the level and start to detect it as you made it but i improved it a little

sure, u can get access, but i didnt know how to give it

**Comment by bakhti31** [comment]
done invited
